apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: deploy-template
spec:
  params:
    - default: default
      name: serviceAccount
  ytt: |
    #@ load("@ytt:data", "data")

    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: #@ data.values.workload.metadata.name
    spec:
      serviceAccountName: #@ data.values.params.serviceAccount
      fetch:
        - inline:
            paths:
              config.yml: |
                ---
                apiVersion: kapp.k14s.io/v1alpha1
                kind: Config
                rebaseRules:
                  - path: [metadata, annotations, serving.knative.dev/creator]
                    type: copy
                    sources: [new, existing]
                    resourceMatchers: &matchers
                      - apiVersionKindMatcher: {apiVersion: serving.knative.dev/v1, kind: Service}
                  - path: [metadata, annotations, serving.knative.dev/lastModifier]
                    type: copy
                    sources: [new, existing]
                    resourceMatchers: *matchers
        - inline:
            pathsFrom:
            - configMapRef:
                name: #@ data.values.workload.metadata.name
      template:
        - ytt: {}
      deploy:
        - kapp: {}