apiVersion: v1
kind: List
items:
  - apiVersion: carto.run/v1alpha1
    kind: ClusterSupplyChain
    metadata:
      name: source-to-url
    spec:
      selector:
        apps.tanzu.vmware.com/workload-type: web
      resources:
        - name: source-provider
          params:
            - name: serviceAccount
              value: tap-sa
          templateRef:
            kind: ClusterSourceTemplate
            name: source-template
        - name: image-builder
          params:
            - name: serviceAccount
              value: tap-sa
            - name: clusterBuilder
              value: default
            - name: registry
              value:
                repository: tap
                server: harbor.tap.amer.end2end.link
          sources:
            - name: source
              resource: source-provider
          templateRef:
            kind: ClusterImageTemplate
            name: kpack-template
        - images:
            - name: image
              resource: image-builder
          name: config-provider
          params:
            - name: serviceAccount
              value: tap-sa
          templateRef:
            kind: ClusterConfigTemplate
            name: convention-template
        - configs:
            - name: config
              resource: config-provider
          name: app-deploy
          params:
            - name: serviceAccount
              value: tap-sa
          templateRef:
            kind: ClusterTemplate
            name: deploy-template
        - configs:
            - name: config
              resource: config-provider
          name: app-config
          templateRef:
            kind: ClusterTemplate
            name: config-template
